### ISSUE TITLE
Uniques dropped with Implicit slider enabled drop with broken bases

### ISSUE THREAD

**Issue by Silver-D** [RCInet/LastEpoch_Mods#14]
If you naturally drop a Unique (say from a Monolith boss or from a prophecy), the base of the item will be all screwed up -- like Helmets will always be Jeweled Cirlcets, Armors will be Leather etc.

I fixed it in Items_Drop_Implicits on line 36 in the CanRun() block by adding a check to see if the item is a unique or set.

``if (!__instance.isUniqueSetOrLegendary())
{
                        __instance.RefreshIDAndValues();
}
                    return false;
``

Seems to work correctly with both normal items and uniques now. I haven't disassembled the game yet myself, so not sure if this is *actually* a good fix.

As a side note, it would really help to have an option to disable the silly Combat log and HeadHunter processing in the config file. I had to uncomment their loading entirely, as they lag my system to unimaginable slowdown during fights. Regardless if i set them to disabled, only worked by completely uncommenting their compilation in .csproject
(I'm on Linux playing in Wine, maybe that's why. 0.5.7 of MelonLoader doens't have native Linux support yet, boo!)

Amazing mod though. Absolutely cannot play the game without it. Superb. Thank you so much sir.

**Comment by Trohed** [comment]
Hello Silver-D... would it be possible to share a version of the source files (project) with your modifications?

**Comment by Silver-D** [comment]
> Hello Silver-D... would it be possible to share a version of the source files (project) with your modifications?

Hi! I'm not sure if I should publically publish anything without the author's permission, and I certainly did some "personal touches", disabled some things, and only fixed a few that only matter to my playthrough. But it is also not in a condition to be a proper fork of the project.

Send me an email (click on my profile) and I'll send you a google drive link

**Comment by RCInet** [comment]
__instance.RefreshIDAndValues(); is like a save item
Removin it from implicit  = you can't set implicit for unique and set

We have to debug to see what append because we don't edit item subtype
In any item_drop hook (in all Items_Drop_XXX.cs)

Before doing anything
`ushort subtype = __instance.subType; //backup subtype`

After __instance.RefreshIDAndValues();
`if (subtype != __instance.subType)
{
    Main.logger_instance.Error("ItemData.randomiseUniqueRolls() ItemData.subType change from " + subtype + " to " + __instance.subType);
    __instance.subType = subtype;
}`

Open your game with this, then wait for an error

**Comment by Silver-D** [comment]
Yup, got the error on every single Set item that dropped from a prophecy -- 

I had Implicit rolls enabled to 100% value, and nothing else.

```
[11:37:04.830] [LastEpoch_Hud] [ERROR] ItemData.randomiseImplicitRolls() ItemData.subType change from 4 to 1
[11:37:04.834] [LastEpoch_Hud] [ERROR] ItemData.randomiseImplicitRolls() ItemData.subType change from 2 to 1
[11:37:04.838] [LastEpoch_Hud] [ERROR] ItemData.randomiseImplicitRolls() ItemData.subType change from 4 to 1
[11:37:04.842] [LastEpoch_Hud] [ERROR] ItemData.randomiseImplicitRolls() ItemData.subType change from 2 to 1
[11:37:04.846] [LastEpoch_Hud] [ERROR] ItemData.randomiseImplicitRolls() ItemData.subType change from 4 to 1
[11:37:04.847] [LastEpoch_Hud] [ERROR] ItemData.randomiseImplicitRolls() ItemData.subType change from 5 to 1
[11:37:06.721] [LastEpoch_Hud] [ERROR] ItemData.randomiseImplicitRolls() ItemData.subType change from 3 to 1
```
Now, when you set ``__instance.subType = subtype`` when the error happens, that does fix it.

Without this assignment, I get junk like this:

![image](https://github.com/user-attachments/assets/c8501b90-4eee-4a59-b6b3-dd44ff0154dc)

Clearly not a jeweled socket [https://www.lastepochtools.com/db/items/UAzCsNI](url) xD

Full code for reference : Items_Drop_Implicits.cs

```
ushort subtype = __instance.subType; //backup subtype

for (int z = 0; z < __instance.implicitRolls.Count; z++)
{
    /// snip implicitValue[k] = v;
}
__instance.RefreshIDAndValues();

if (subtype != __instance.subType) { 
  Main.logger_instance.Error("ItemData.randomiseImplicitRolls() ItemData.subType change from " + subtype + " to " + __instance.subType); 
/*__instance.subType = subtype;*/ 
}
return false;
```

**Comment by RCInet** [comment]
Better using game function ^^ (Make a new class "Items_UniqueList_SubType", then add this code)

`
using HarmonyLib;

namespace LastEpoch_Hud.Scripts.Mods.Items
{
    public class Items_UniqueList_SubType
    {
        [HarmonyPatch(typeof(UniqueList.Entry), "GetSubType")]
        public class UniqueList_Entry_GetSubType
        {
            [HarmonyPrefix]
            static bool Prefix(UniqueList.Entry __instance, ref ushort __result/*, UniqueList.SubTypePreference __0, byte __1*/)
            {
                bool ret = true;
                //if (Scenes.IsGameScene())     //Uncomment this part if you don't want items to be repair when loading your character
                //{
                    byte unique_subtype = __instance.subTypes[0]; //Subtype from unique list
                    if (__result != unique_subtype)
                    {
                        Main.logger_instance.Msg("UniqueList.Entry.GetSubType(), result = " + __result + " set to " + unique_subtype + " (Unique.Subtype from list)"); //Comment if you don't want to see debug log
                        __result = unique_subtype;
                        ret = false;            //Don't load UniqueList.Entry.GetSubType(), we already have the result we need
                }
                //}
                return ret;
            }
        }
    }
}
`

**Comment by Silver-D** [comment]
I got a lot of the same logs when I loaded my character, but it still drops Jeweled Circlets.
Was I supposed to keep the code changes we did for Implicit affixed? i don't see that file in the commit history, so I removed the code.

**Comment by RCInet** [comment]
As you wish, but if you keep your code, you should do the same in Items_Drop_UniqueMods.cs (same issue)

My snippet force the result of UniqueList.Entry.GetSubType() to be the good result (tried with 40+ items), append only for unique set and legendary, and fix the 2 issues.

**Comment by Silver-D** [comment]
Wait wait hang on. What I'm saying is -- I don't think it's fully fixed in the repository --

I pulled all of your changes from the repository, clean code.
I set Implicit Rolls value to a range.
I went and killed a boss for a prophecy, and got wrong Item Types as drops for my sets (as the issue originally was).
Now, when I _reloaded_ my character, with your new changes, then the items were fixed.

But -- what I'm saying is, if you're setting Implicit Roll Range %, then Uniques and Sets --they still initially drop with the wrong subtype, if we're not using any additional code. Maybe _backupSubtype is needed in the ImplicitRolls code? because without it it's dropping bad uniques.

And all we're doing is increasing Implicit Value Range %, nothing else

**Comment by RCInet** [comment]
I'm tired, sorry, we can't do a check in a [HarmonyPrefix] because function start after, so your code should be set in a [HarmonyPostfix] (after the function)
My code have the same issue ^^ 
You're fix is only visual (game repair your item when loading a character), mine not work as intend because item isn't created

We have to edit your item when item drop on ground (GroundItemManager), set real SubType on item then save it

**Comment by Trohed** [comment]
Hi... I'm testing the latest patch and see the problem still persists
Correct Isadora's Tomb Binding
![image](https://github.com/user-attachments/assets/22a90ef1-a3ac-40e8-b5b9-3236c8978881)

This case happens with all items as far as I can see...on the left, drop, on the right, valid values
to fix this issue in the current patch, immediately after dropping the item go to the mod's config and disable then enable any parameter that will display the correct values

![image](https://github.com/user-attachments/assets/6e3ee265-0533-45da-aa10-587ba3e776bf)
![image](https://github.com/user-attachments/assets/c5367481-d8c0-4fb9-a53a-11e5333a6948)
![image](https://github.com/user-attachments/assets/5ef3b3de-ff8a-4b45-bd48-a28dba48bc63)

**Comment by Silver-D** [comment]
Huh. Interesting. The Display of the subtype is now correct, but the implicit values are all broken.

Currently I'm a little busy trying to port the Skins mod and my new small Mod to a new framework (will be seperate project/mod) for easy and quick Mod making, as to not bombard this excellent author with silly small requests.

But I'll take a look at it later tonight if the issue still isn't fixed!

**Comment by Trohed** [comment]
This is probably not just a visual issue, as both versions provide different stats when equipped

**Comment by Trohed** [comment]
This is probably not just a visual issue, as both versions provide different stats when equipped.


Silver-D is what you recently emailed me after testing... it shows correctly both statistically and visually. If you come up with something new, I'd love to test it

**Comment by Silver-D** [comment]
Right, but I've been doing this for about 2-3 days, where RCINet has been digging at the code for months and months.

What I did was _seemingly_ correct, as in I bypassed a function that saved an item during Implicit rolls. Now if he says that's not a very good idea, I believe him.

The other option (in the code above) was to do a _backup_subtype before __instance.RefreshIDAndValues(); , and then restoring it after.  (look at the comments above with the code I did. That also worked).
But that kind of defeats the whole purpose of RefreshIDAndValues(). 

I don't know why we can't skip RefreshIDAndValues at the time when the item doesn't even have any implicit rolls and the item barely exists, but like I said, I'm not experienced in the way the game works internally.

One _other_ idea I have is to do everything we need to do at the function DropItemAtPoint -- 
``[HarmonyPatch(typeof(GenerateItems), "DropItemAtPoint")]`` in ``Items_Drop_Affixs.cs``

We can probably re-roll implicit Affixes and I _100%_know for a fact_ we can safely roll Unique Mod Ranges there, too. I have tested this Unique Mods there in the build I sent you.
My idea here is to move everything regarding Implicit and Unique Mod re-rolls to DropItemAtPlayer in Items_Drop_Affixs.cs, as that is one Safe place where we can re-roll everything (it seems like!), and have a safe way to do RefreshIDAndValues there as well.

But I haven't tested this with Implicits yet.

But fixing items on the fly and in inventory is a  bit convoluted, I think...? especially since we want to look at the correct tooltip on the ground. And at the end of the day, all we really want to do is reroll a few values.

**Comment by RCInet** [comment]
For debugging this, drop an item on ground and use UnityExplorer

Open UnityExplore and search for GroundItemManager Class
Open it then go "instance", then "offline items", then items
Drop your item, use "update display value" on inspector, your item should pop in the list, open it, go to "ItemData", you can see all the values

With this i can see, in implicits, there are property (copy from UniqueList your implicits and it's done)
![Uploading Screen.png…]()

**Comment by Silver-D** [comment]
Oh my god I had no idea UnityExplorer existed. Holy crap that tool looks amazing and will make things much simpler, if I can get it to work on linux haha.

You have a bug in the code:

1) You're choosing a random number from 0 to the _number of subtypes an item can have_, which is most likely from 0 to 1 (so it always rolls 0). ``int rand = UnityEngine.Random.RandomRangeInt(0, unique.subTypes.Count);`` Then that number is assigned as a subtype -- not a random number from the subtypes that are actually in the list `` __1.subType = (ushort)rand;  __1.id[2] = (byte)rand; //subtype``

2) We're breaking a Unique and Set items during ``[HarmonyPatch(typeof(ItemData), "randomiseUniqueRolls")]`` and then we're repairing it at ``[HarmonyPatch(typeof(GenerateItems), "DropItemAtPoint")]``. What happens when we have a Unique as a reward for something likeNemesis ? (Where you can choose the Unique that it generates form a popup window). 

Is there no way how we can not break the subtype in the first place during  randomiseUniqueRolls or potentially, as you say it happens, during ``randomiseUniqueRolls``?

Something about randomizing a subtype that the game didn't drop doesn't sit right with me -- some Unique subtypes could be disabled from dropping, and we're potentially forcing them with a Random roll. Maybe save the initial subtype somewhere during those times when it breaks, and then restore them later?

**Comment by RCInet** [comment]
Search for "UnityEngine.Random.RandomRangeInt" and you can see how this is working
Ex : UnityEngine.Random.RandomRangeInt(10,20); = range 10 - 19

**Comment by Silver-D** [comment]
No, no, I know. But what you're doing is 

```
int rand = UnityEngine.Random.RandomRangeInt(0, unique.subTypes.Count);
__1.subType = rand;
 __1.id[2] = rand; //subtype
```

^^ You're getting a random _number_ of subTypes and then assigning that _number of subtypes_ to _a subtype_

When it should be

```
int rand = UnityEngine.Random.RandomRangeInt(0, unique.subTypes.Count);
 __1.subType = unique.subTypes[rand];
__1.id[2] = unique.subTypes[rand]; //subtype
```

**Comment by RCInet** [comment]
OMG ^^
